version: '3'
services:
  java:
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DB_USER=postgres
      - DB_PASSWORRD=test
      - DB_URL=jdbc:postgresql://db:5432/test
    volumes:
      - ..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: test
  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080